// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHhjIOW4KQE5yhCMr-2F26clSAGkjaMiY',
    appId: '1:546349392825:web:2dc7b54f98853214e2cc68',
    messagingSenderId: '546349392825',
    projectId: 'chatapp-5d71c',
    authDomain: 'chatapp-5d71c.firebaseapp.com',
    storageBucket: 'chatapp-5d71c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD80qxMHkOY4IGLuVVdoe7skpq14zKisss',
    appId: '1:546349392825:android:8805218b83973ed5e2cc68',
    messagingSenderId: '546349392825',
    projectId: 'chatapp-5d71c',
    storageBucket: 'chatapp-5d71c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXnjOwfb1Lf-l2IZaKitSQwkL9_oKyCos',
    appId: '1:546349392825:ios:ef8867e36ffed267e2cc68',
    messagingSenderId: '546349392825',
    projectId: 'chatapp-5d71c',
    storageBucket: 'chatapp-5d71c.firebasestorage.app',
    iosBundleId: 'com.example.monsyWeirdPackage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXnjOwfb1Lf-l2IZaKitSQwkL9_oKyCos',
    appId: '1:546349392825:ios:ef8867e36ffed267e2cc68',
    messagingSenderId: '546349392825',
    projectId: 'chatapp-5d71c',
    storageBucket: 'chatapp-5d71c.firebasestorage.app',
    iosBundleId: 'com.example.monsyWeirdPackage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHhjIOW4KQE5yhCMr-2F26clSAGkjaMiY',
    appId: '1:546349392825:web:1bda19d62a62c0eee2cc68',
    messagingSenderId: '546349392825',
    projectId: 'chatapp-5d71c',
    authDomain: 'chatapp-5d71c.firebaseapp.com',
    storageBucket: 'chatapp-5d71c.firebasestorage.app',
  );
}
